Fix TestBundleValidate
Updates https://github.com/google/gvisor/issues/10045

Before:

```
--- FAIL: TestBundleValidate (0.00s)
    --- FAIL: TestBundleValidate/invalid_value (0.00s)
        config_test.go:713: Validate failed: mismatch error: got: "parse error" want: "parsing \"invalid\": invalid syntax"
FAIL
```

Different flags is used in OSS and internal versions, check comment below.

FUTURE_COPYBARA_INTEGRATE_REVIEW=https://github.com/google/gvisor/pull/11722 from stepancheg:fix-test-bundle-validate 334c56f6554eb946feb351febf6f077d3af7437f
PiperOrigin-RevId: 758491289